name: exercise
on: [push, workflow_dispatch]

jobs:

  everything-all-at-once:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies.
        run: yarn

      - name: Build.
        run: yarn build

      - name: Execute unit tests.
        run: yarn test

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit

      - name: Execute e2e tests.
        run: yarn test:e2e

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: E2E Tests
          path: 'reports/cypress-*.xml'
          reporter: jest-junit