name: exercise
on: [push, workflow_dispatch]

jobs:

  everything-all-at-once:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies.
        run: yarn

      - name: Build.
        run: yarn buld

      - name: Execute unit tests.
        run: yarn test
        
      - name: Execute e2e tests.
        run: yarn test:e2e