name: exercise-split
on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install 
        run: yarn
      
      - name: Execute unit tests.
        run: yarn test

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit


  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies.
        run: yarn
      
      - name: Build.
        run: yarn build
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: public
          retention-days: 1

      - name: E2E Tests.
        run: yarn test:e2e

      - name: Collect test reports.
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'reports/*.xml'