name: exercise-split
on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies.
        run: yarn
      - name: Build.
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: public
          retention-days: 1


  unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install 
        run: yarn
      - name: Execute unit tests.
        run: yarn test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit

  e2e:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: [ chrome ]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies.
        run: yarn
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: public
      - name: Execute e2e tests.
        env:
          CYPRESS_OPTS: '--browser=${{ matrix.browser }}'
        run: yarn test:e2e
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: E2E Tests
          path: 'reports/cypress-*.xml'
          reporter: jest-junit
