name: exercise-split
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies.
        run: yarn
      - name: Build.
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: public
          retention-days: 1


  unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install 
        run: yarn
      - name: Execute unit tests.
        run: yarn test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit

  e2e:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        # currently connetion to firefox can not be established, turn it of for now
        # browser: [ chrome, firefox ]
        browser: [ chrome ]

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: public

      - name: E2E Tests.
        run: yarn test:e2e
        # env:
        #   CYPRESS_OPTS: '--browser=${{ matrix.browser }}'

      - name: Collect test reports.
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'reports/*.xml'