name: example-wf
on: [push, workflow_dispatch]

jobs:
  print-something-to-logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my workflow!"
      - run: echo "This is another step."

  print-another-thing-to-logs:
    runs-on: ubuntu-latest
    needs: [print-something-to-logs]
    steps:
    - run: echo "This is my workflow!"
    - run: echo "This is another step."