name: example-wf
on: [push]

jobs:
  print-something-to-logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my workflow!"
      - run: echo "This is another step."
      - run: apt update

  print-another-thing-to-logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my workflow!"
      - run: echo "This is another step."
      - run: apt update